# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewFigWindow(object):
    def setupUi(self, NewFigWindow):
        NewFigWindow.setObjectName("NewFigWindow")
        NewFigWindow.resize(307, 160)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        NewFigWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(NewFigWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.xlaLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(7)
        self.xlaLabel.setFont(font)
        self.xlaLabel.setObjectName("xlaLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.xlaLabel)
        self.xlaLlineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.xlaLlineEdit.setObjectName("xlaLlineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.xlaLlineEdit)
        self.ylaLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(7)
        self.ylaLabel.setFont(font)
        self.ylaLabel.setObjectName("ylaLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ylaLabel)
        self.ylaLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.ylaLineEdit.setObjectName("ylaLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ylaLineEdit)
        self.titLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(7)
        self.titLabel.setFont(font)
        self.titLabel.setObjectName("titLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.titLabel)
        self.titLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.titLineEdit.setObjectName("titLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.titLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.doNewFigButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(7)
        self.doNewFigButton.setFont(font)
        self.doNewFigButton.setObjectName("doNewFigButton")
        self.verticalLayout.addWidget(self.doNewFigButton)
        NewFigWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NewFigWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 307, 22))
        self.menubar.setObjectName("menubar")
        NewFigWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NewFigWindow)
        self.statusbar.setObjectName("statusbar")
        NewFigWindow.setStatusBar(self.statusbar)

        self.retranslateUi(NewFigWindow)
        self.doNewFigButton.clicked.connect(NewFigWindow.doNewFigButtonOnClicked)
        QtCore.QMetaObject.connectSlotsByName(NewFigWindow)

    def retranslateUi(self, NewFigWindow):
        _translate = QtCore.QCoreApplication.translate
        NewFigWindow.setWindowTitle(_translate("NewFigWindow", "新建图片"))
        self.xlaLabel.setText(_translate("NewFigWindow", "请输入x轴单位"))
        self.ylaLabel.setText(_translate("NewFigWindow", "请输入y轴单位"))
        self.titLabel.setText(_translate("NewFigWindow", "请输入图片名称"))
        self.doNewFigButton.setText(_translate("NewFigWindow", "确认新建"))
